version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: US/Central
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'composer'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '08:00'
      timezone: US/Central
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'npm'
