version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Europe/London
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'composer'
    groups:
      prod-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Europe/London
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'npm'
    groups:
      prod-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
