version: 2
updates:
  - package-ecosystem: composer
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Europe/London
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'composer'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '10:00'
      timezone: Europe/London
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'npm'
